
export const questions = [
    "Acceptance of Terms of Service",
    "Who may use our Services (User)",
    "Materials relate to our Services",
    "Users' Obligations",
    "Trademark Issue",
    "Copyright Issue",
];

export const answers = [
    "Snapinsta creates and develops content, information, graphics, documents, text, products, and all other elements and products and services offered through Snapinsta App and Web (Content or Materials) available for your use for free and personal use subject to the terms and conditions set out in this document. By accessing and using Snapinsta App and Web you agree to be bound by and to accept our ToS and all terms and conditions contained and/or referenced herein, and you agree to abide by the ToS as a User (Users) of our Content and Materials.",

    "You agree to use Snapinsta App and Web, Snapinsta Products and Services only for purposes permitted by our ToS as well as any applicable law, regulation or generally accepted practices or guidelines in the relevant jurisdictions. Our tools were designed to help you download videos and images uploaded by your own account. We reserve the right to refuse to provide our service if you use our tools to infringe upon others people privacy and material. SNAPINSTA IS NOT RESPONSIBLE FOR ANY VIOLATION OF APPLICABLE LAWS, RULES, OR REGULATIONS COMMITTED BY YOU OR A THIRD PARTY AT YOUR BEHEST. Specifically, you agree and warrant that in using Snapinsta App and Web, Snapinsta Products and Services, your actions do not contravene the laws, rules, or regulations of (1) the country, state, or locality where you reside, or (2) the country, state, or locality where Snapinsta is located or operates.",

    "Snapinsta respects trademark rights and complies with trademark laws and regulations. Our trademark Snapinsta™ is created by Snapinsta and should be used only for and in relation to our Services, Snapinsta App and Web. It should be read as a seamless word without reference to any individual or entity other than Snapinsta. When using, mentioning, referring to our Services, Snapinsta App and Web, Snapinsta Content and Materials, please note to follow our policy: - Use the exact format Snapinsta™ as a word without any space, division, separation among its constituent components or in any other variants. - Never associate our trademark Snapinsta™ with and never confuse our Snapinsta TM with any other individual(s), entity(ies), application(s), website(s), goods or services of other individual and entities if not belong to Snapinsta. - We reserve our rights in and relating to our trademark Snapinsta™ against any misuse, misrepresentation, infringement in any form. - We encourage and thank you who inform us of any suspect misuse, misrepresentation, infringement, and non-compliance for our proper handling.",

    "You agree to use Snapinsta App and Web, Snapinsta Products and Services only for purposes permitted by our ToS as well as any applicable law, regulation or generally accepted practices or guidelines in the relevant jurisdictions. Our tools was designed to help you download videos and images uploaded by your own account. We reserve the right to refuse to provide our service if you use our tools to infringe upon others people privacy and material.SNAPINSTA IS NOT RESPONSIBLE FOR ANY VIOLATION OF APPLICABLE LAWS, RULES, OR REGULATIONS COMMITTED BY YOU OR A THIRD PARTY AT YOUR BEST,Specifically, you agree and warrant that in using Snapinsta App and Web, Snapinsta Products and Services, your actions do not contravene the laws, rules, or regulations of (1) the country, state, or locality where you reside, or (2) the country, state, or locality where Snapinsta is located or operates.",

    "Snapinsta respects trademark rights and complies with trademark laws and regulations. Our trademark Snapinsta™ is created by Snapinsta and should be used only for and in relation to our Services, Snapinsta App and Web. It should be read as a seamless word without reference to any individual or entity other than Snapinsta. When using, mentioning, referring to our Services, Snapinsta App and Web, Snapinsta Content and Materials, please note to follow our policy: Use the exact format Snapinsta™ as a word without any space, division, separation among its constituent components or in any other variants. Never associate our trademark Snapinsta™ with and never confuse our Snapinsta TM with any other individual(s), entity(ies), application(s), website(s), goods or services of other individual and entities if not belong to Snapinsta. We reserve our rights in and relating to our trademark Snapinsta™ against any misuse, misrepresentation, infringement in any form. We encourage and thank you who inform us of any suspect misuse, misrepresentation, infringement, and non-compliance for our proper handling.",
    
    "Snapinsta respects copyrights and complies with copyright laws and regulations. Users are responsible for the content you use with (the link you paste on) Snapinsta App and Web. Snapinsta provides support to Users to download information/content Users paste on Snapinsta App and Web for the legitimate interests of the Users. We only display 'as is' content that users have posted on websites, pages or networks of service or social network providers. Users are responsible for ensuring they have the legal right in accordance with relevant laws and ensure their own intellectual property rights in relation to the content as posted. Users only use video downloaded through the Snapinsta App and Web, for personal, non-commercial, free purposes. Snapinsta cannot and has no obligation to check whether each content/information is legal or not, but if it detects any violation, it will ban Users from accessing and using Snapinsta App and Web and Snapinsta Products and Services. Snapinsta does not backup/archive Users’ content for any reason. We encourage and thank you who inform us of any suspect misuse, misrepresentation, unauthorized use, infringement and non-compliance for our proper handling."
];
